import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const dir = path.join(process.cwd(), "..", ".obsidian", "plugins", "liquid-notes");

if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(dir, "main.js"),
	minify: prod,
});

// Helper to copy manifest and styles
const copyFiles = () => {
    fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
    if (fs.existsSync("styles.css")) {
        fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
    }
};

if (prod) {
    copyFiles();
	await context.rebuild();
	process.exit(0);
} else {
    copyFiles();
	await context.watch();
}
